package Medicure;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.time.LocalDateTime;
import java.util.Random;
import javax.swing.DefaultListModel;

public class MainUI extends javax.swing.JFrame {
    
    public MainUI() {
		//Initialize UI and its components
        initComponents();
		
		//Setting icon for the program from the imported project resource
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("medicine.png")));
		
		//Setting background color of the form pane
        getContentPane().setBackground(new Color(20, 20, 20));
    }
    
	//The list of all PatientInfo classes to store a collection of data
	//We are gonna use this array list as our database/data source for the program
    ArrayList<PatientInfo> database = new ArrayList<>();
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientsList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        __ID = new javax.swing.JTextField();
        __name = new javax.swing.JTextField();
        __age = new javax.swing.JTextField();
        __gender = new javax.swing.JTextField();
        __address = new javax.swing.JTextField();
        __phonenumber = new javax.swing.JTextField();
        __disease = new javax.swing.JTextField();
        __billamount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        __regdate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        __email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        __appointeddoctor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        __roomnumber = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        __bednumber = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        __condition = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        __adharnumber = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        bednumber__ = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        name__ = new javax.swing.JTextField();
        condition__ = new javax.swing.JTextField();
        age__ = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        gender__ = new javax.swing.JTextField();
        adharnumber__ = new javax.swing.JTextField();
        address__ = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        phonenumber__ = new javax.swing.JTextField();
        disease__ = new javax.swing.JTextField();
        billamount__ = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        email__ = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        appointeddoctor__ = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        roomnumber__ = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        userName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medicure - Control centre");
        setBackground(new java.awt.Color(20, 20, 20));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("+ MEDICURE");

        jLabel2.setFont(new java.awt.Font("Orbitron", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(50, 50, 50));
        jLabel2.setText("Prevention is better than cure");

        jLabel3.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 70, 70));
        jLabel3.setText("Patients database");

        patientsList.setBackground(new java.awt.Color(25, 25, 25));
        patientsList.setForeground(new java.awt.Color(255, 255, 255));
        patientsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        patientsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                patientsListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(patientsList);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(90, 90, 90));
        jLabel4.setText("Patient ID");

        jLabel5.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(90, 90, 90));
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(90, 90, 90));
        jLabel6.setText("Age");

        jLabel7.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(90, 90, 90));
        jLabel7.setText("Gender");

        jLabel8.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(90, 90, 90));
        jLabel8.setText("Phone no.");

        jLabel9.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(90, 90, 90));
        jLabel9.setText("Disease");

        jLabel10.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(90, 90, 90));
        jLabel10.setText("Bill Amount");

        jLabel11.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(90, 90, 90));
        jLabel11.setText("Address");

        __ID.setBackground(new java.awt.Color(25, 25, 25));
        __ID.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        __ID.setForeground(new java.awt.Color(255, 255, 255));
        __ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                __IDActionPerformed(evt);
            }
        });

        __name.setBackground(new java.awt.Color(25, 25, 25));
        __name.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        __name.setForeground(new java.awt.Color(255, 255, 255));

        __age.setBackground(new java.awt.Color(25, 25, 25));
        __age.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        __age.setForeground(new java.awt.Color(255, 255, 255));

        __gender.setBackground(new java.awt.Color(25, 25, 25));
        __gender.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        __gender.setForeground(new java.awt.Color(255, 255, 255));

        __address.setBackground(new java.awt.Color(25, 25, 25));
        __address.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        __address.setForeground(new java.awt.Color(255, 255, 255));

        __phonenumber.setBackground(new java.awt.Color(25, 25, 25));
        __phonenumber.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        __phonenumber.setForeground(new java.awt.Color(255, 255, 255));

        __disease.setBackground(new java.awt.Color(25, 25, 25));
        __disease.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        __disease.setForeground(new java.awt.Color(255, 255, 255));

        __billamount.setBackground(new java.awt.Color(25, 25, 25));
        __billamount.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        __billamount.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(90, 90, 90));
        jLabel12.setText("Reg. Date");

        __regdate.setBackground(new java.awt.Color(25, 25, 25));
        __regdate.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        __regdate.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(90, 90, 90));
        jLabel13.setText("Email");

        __email.setBackground(new java.awt.Color(25, 25, 25));
        __email.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        __email.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(90, 90, 90));
        jLabel14.setText("Appointed Doctor");

        __appointeddoctor.setBackground(new java.awt.Color(25, 25, 25));
        __appointeddoctor.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        __appointeddoctor.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(90, 90, 90));
        jLabel15.setText("Room no.");

        __roomnumber.setBackground(new java.awt.Color(25, 25, 25));
        __roomnumber.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        __roomnumber.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(90, 90, 90));
        jLabel16.setText("Bed no.");

        __bednumber.setBackground(new java.awt.Color(25, 25, 25));
        __bednumber.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        __bednumber.setForeground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(90, 90, 90));
        jLabel17.setText("Condition");

        __condition.setBackground(new java.awt.Color(25, 25, 25));
        __condition.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        __condition.setForeground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(90, 90, 90));
        jLabel18.setText("Adhar no.");

        __adharnumber.setBackground(new java.awt.Color(25, 25, 25));
        __adharnumber.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        __adharnumber.setForeground(new java.awt.Color(255, 255, 255));

        updateBtn.setBackground(new java.awt.Color(25, 25, 25));
        updateBtn.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 0, 51));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(1, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel20.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(90, 90, 90));
        jLabel20.setText("Name");

        jLabel21.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(90, 90, 90));
        jLabel21.setText("Age");

        jLabel22.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(90, 90, 90));
        jLabel22.setText("Gender");

        jLabel23.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(90, 90, 90));
        jLabel23.setText("Bed no.");

        bednumber__.setBackground(new java.awt.Color(25, 25, 25));
        bednumber__.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        bednumber__.setForeground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(90, 90, 90));
        jLabel24.setText("Condition");

        name__.setBackground(new java.awt.Color(25, 25, 25));
        name__.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        name__.setForeground(new java.awt.Color(255, 255, 255));

        condition__.setBackground(new java.awt.Color(25, 25, 25));
        condition__.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        condition__.setForeground(new java.awt.Color(255, 255, 255));

        age__.setBackground(new java.awt.Color(25, 25, 25));
        age__.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        age__.setForeground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(90, 90, 90));
        jLabel25.setText("Adhar no.");

        gender__.setBackground(new java.awt.Color(25, 25, 25));
        gender__.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        gender__.setForeground(new java.awt.Color(255, 255, 255));

        adharnumber__.setBackground(new java.awt.Color(25, 25, 25));
        adharnumber__.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        adharnumber__.setForeground(new java.awt.Color(255, 255, 255));

        address__.setBackground(new java.awt.Color(25, 25, 25));
        address__.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        address__.setForeground(new java.awt.Color(255, 255, 255));

        addBtn.setBackground(new java.awt.Color(25, 25, 25));
        addBtn.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 0, 51));
        addBtn.setText("Add Entry");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        phonenumber__.setBackground(new java.awt.Color(25, 25, 25));
        phonenumber__.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        phonenumber__.setForeground(new java.awt.Color(255, 255, 255));

        disease__.setBackground(new java.awt.Color(25, 25, 25));
        disease__.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        disease__.setForeground(new java.awt.Color(255, 255, 255));

        billamount__.setBackground(new java.awt.Color(25, 25, 25));
        billamount__.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        billamount__.setForeground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(90, 90, 90));
        jLabel27.setText("Phone no.");

        jLabel28.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(90, 90, 90));
        jLabel28.setText("Email");

        email__.setBackground(new java.awt.Color(25, 25, 25));
        email__.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        email__.setForeground(new java.awt.Color(255, 255, 255));

        jLabel29.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(90, 90, 90));
        jLabel29.setText("Disease");

        jLabel30.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(90, 90, 90));
        jLabel30.setText("Appointed Doctor");

        jLabel31.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(90, 90, 90));
        jLabel31.setText("Bill Amount");

        appointeddoctor__.setBackground(new java.awt.Color(25, 25, 25));
        appointeddoctor__.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        appointeddoctor__.setForeground(new java.awt.Color(255, 255, 255));

        jLabel32.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(90, 90, 90));
        jLabel32.setText("Address");

        jLabel33.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(90, 90, 90));
        jLabel33.setText("Room no.");

        roomnumber__.setBackground(new java.awt.Color(25, 25, 25));
        roomnumber__.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        roomnumber__.setForeground(new java.awt.Color(255, 255, 255));

        jLabel34.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(70, 70, 70));
        jLabel34.setText("Register new patient");

        deleteBtn.setBackground(new java.awt.Color(25, 25, 25));
        deleteBtn.setFont(new java.awt.Font("Orbitron", 0, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 0, 51));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        userName.setFont(new java.awt.Font("Orbitron", 2, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 51, 51));
        userName.setText("Welcome Doctor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__name)
                                    .addComponent(__ID)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__age)
                                    .addComponent(__gender)
                                    .addComponent(__address)
                                    .addComponent(__phonenumber)
                                    .addComponent(__billamount, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(__regdate, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(__email)
                                    .addComponent(__disease)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(__adharnumber)
                                    .addComponent(__condition)
                                    .addComponent(__bednumber)
                                    .addComponent(__roomnumber)
                                    .addComponent(__appointeddoctor)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 248, Short.MAX_VALUE)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel25))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(adharnumber__)
                                            .addComponent(condition__)
                                            .addComponent(bednumber__)
                                            .addComponent(roomnumber__)
                                            .addComponent(appointeddoctor__)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel21))
                                        .addGap(80, 80, 80)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gender__)
                                            .addComponent(address__)
                                            .addComponent(phonenumber__)
                                            .addComponent(billamount__, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(email__)
                                            .addComponent(disease__)
                                            .addComponent(age__)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(123, 123, 123)
                                        .addComponent(name__, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(userName))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(age__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gender__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(address__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phonenumber__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(disease__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(billamount__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(appointeddoctor__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roomnumber__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bednumber__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(condition__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adharnumber__, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__disease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__billamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__regdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__appointeddoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__roomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__bednumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__condition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(__adharnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	//event when the window is opened
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
		
		//Setting the username of PC to show on UI who is currently logged in
        userName.setText("Welcome " + System.getProperty("user.name"));
        
		//Adding some example data (as default data) for tests
        database.add(new PatientInfo(1, "Adarsh Kr.", 15, "Male", "Goa, Div X, Road Y",  "8563866478", 
		"Maleria", 2000, "10/2/2006", "adarshkr@gamil.com", "Dr. MBBS Kumar", 1, 12, "Critical", "JD83HRIUR4IG4UIUG5IU"));
        database.add(new PatientInfo(2, "Doraemon", 22, "Robot", "22nd Century, Japan",  "N/A", "Lack of Brain", 
		84638, "Very Good Question", "nobitakadoraemon@gamil.com", "Dr. Oatker", 2, 13, "Panic", "N/A"));
        database.add(new PatientInfo(3, "Mukesh", 25, "Male", "Mumbai, Somewhere...",  "8659487612", "Cancer", 
		80000, "15/12/2000", "mukeshisrip@gamil.com", "Dr. Unknown", 1, 2, "RIP", "GIUR8IFRGHUFIUEFUFGYW"));
        
		//Calling the custom method to load the data from our database variable (PatientInfo List) to UI JList
        LoadDatabaseToUI();
		
    }//GEN-LAST:event_formWindowOpened

    private void __IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event___IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event___IDActionPerformed

	//Event when the selected value of the JList changed or User selects a value in JList
    private void patientsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_patientsListValueChanged
        // TODO add your handling code here:
		
		//Getting all data of the patient from the selected index
        PatientInfo p = database.get(patientsList.getSelectedIndex());
		
		//Setting the required data to the UI Text Fields for editing
        __ID.setText(""+p.ID);
        __name.setText(p.Name);
        __age.setText(""+p.Age);
        __gender.setText(p.Gender);
        __address.setText(p.Address);
        __phonenumber.setText(p.PhoneNumber);
        __disease.setText(p.Disease);
        __billamount.setText(""+p.BillAmount);
        __regdate.setText(p.RegistrationDate);
        __email.setText(p.Email);
        __appointeddoctor.setText(p.AppointedDoctor);
        __roomnumber.setText(""+p.RoomNumber);
        __bednumber.setText(""+p.BedNumber);
        __condition.setText(p.Condition);
        __adharnumber.setText(p.AdharNumber);
    }//GEN-LAST:event_patientsListValueChanged

	//Event when user pressed the Update button
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        
		//a Try-Cache to avoid throwing exceptions for anything
        try
        {
			
            database.remove(patientsList.getSelectedIndex());
        
            __ID.setText("");
            __name.setText("");
            __age.setText("");
            __gender.setText("");
            __address.setText("");
            __phonenumber.setText("");
            __disease.setText("");
            __billamount.setText("");
            __regdate.setText("");
            __email.setText("");
            __appointeddoctor.setText("");
            __roomnumber.setText("");
            __bednumber.setText("");
            __condition.setText("");
            __adharnumber.setText("");
        
            LoadDatabaseToUI();
        }
        catch(Exception ec)
        {
        
        }
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        try
        {
            PatientInfo p = database.get(patientsList.getSelectedIndex());
        
            p.ID = Integer.parseInt(__ID.getText());
            p.Name = __name.getText();
            p.Age = Integer.parseInt(__age.getText());
            p.Gender = __gender.getText();
            p.Address = __address.getText();
            p.PhoneNumber = __phonenumber.getText();
            p.Disease = __disease.getText();
            p.BillAmount = Integer.parseInt(__billamount.getText());
            p.RegistrationDate = __regdate.getText();
            p.Email = __email.getText();
            p.AppointedDoctor = __appointeddoctor.getText();
            p.RoomNumber = Integer.parseInt(__roomnumber.getText());
            p.BedNumber = Integer.parseInt(__bednumber.getText());
            p.Condition = __condition.getText();
            p.AdharNumber = __adharnumber.getText();
        
            database.set(patientsList.getSelectedIndex(), p);
        }
        catch(Exception ec)
        {
        
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        try
        {
            Random rnd = new Random();
            database.add(new PatientInfo(rnd.nextInt(999999999), name__.getText(), Integer.parseInt(age__.getText()), gender__.getText(), address__.getText(),  phonenumber__.getText(), disease__.getText(), Integer.parseInt(billamount__.getText()), LocalDateTime.now().toString(), email__.getText(), appointeddoctor__.getText(), Integer.parseInt(roomnumber__.getText()), Integer.parseInt(bednumber__.getText()), condition__.getText(), adharnumber__.getText()));
        
            LoadDatabaseToUI();
        }
        catch(Exception ec)
        {
            
        }
        
    }//GEN-LAST:event_addBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++)
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
        
    }
    
	//Our custom method to load all data from the database (PatientInfo list) to UI JList
    public void LoadDatabaseToUI()
    {
		//clearning the JList
        patientsList.removeAll();
		
		//Declaring a new List Model to set in JList
        DefaultListModel values = new DefaultListModel();
		
		//Iterating through all elements of the database
        for(int i=0; i<database.size(); i++)
        {
			//Adding the names each Patient name from the currrent database
            values.addElement(database.get(i).Name);
        }
		
		//Setting our declared model to the JList to show in UI
        patientsList.setModel(values);
    }
    
	//Our custom class to store managed data into
    public class PatientInfo {
        public int ID;
        public String Name;
        public int Age;
        public String Gender;
        public String Address;
        public String PhoneNumber;
        public String Disease;
        public int BillAmount;
        public String RegistrationDate;
        public String Email;
        public String AppointedDoctor;
        public int RoomNumber;
        public int BedNumber;
        public String Condition;
        public String AdharNumber;
        
        PatientInfo(int _id, String _name, int _age, String _gender, String _address, String _phoneNumber, 
		String _disease, int _billAmount, String _registrationDate, String _email, String _appointedDoctor, 
		int _roomNumber, int _bedNumber, String _condition, String _adharNumber)
        {
            ID = _id;
            Name = _name;
            Age = _age;
            Gender = _gender;
            Address = _address;
            PhoneNumber = _phoneNumber;
            Disease = _disease;
            BillAmount = _billAmount;
            RegistrationDate = _registrationDate;
            Email = _email;
            AppointedDoctor = _appointedDoctor;
            RoomNumber = _roomNumber;
            BedNumber = _bedNumber;
            Condition = _condition;
            AdharNumber = _adharNumber;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField __ID;
    private javax.swing.JTextField __address;
    private javax.swing.JTextField __adharnumber;
    private javax.swing.JTextField __age;
    private javax.swing.JTextField __appointeddoctor;
    private javax.swing.JTextField __bednumber;
    private javax.swing.JTextField __billamount;
    private javax.swing.JTextField __condition;
    private javax.swing.JTextField __disease;
    private javax.swing.JTextField __email;
    private javax.swing.JTextField __gender;
    private javax.swing.JTextField __name;
    private javax.swing.JTextField __phonenumber;
    private javax.swing.JTextField __regdate;
    private javax.swing.JTextField __roomnumber;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField address__;
    private javax.swing.JTextField adharnumber__;
    private javax.swing.JTextField age__;
    private javax.swing.JTextField appointeddoctor__;
    private javax.swing.JTextField bednumber__;
    private javax.swing.JTextField billamount__;
    private javax.swing.JTextField condition__;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField disease__;
    private javax.swing.JTextField email__;
    private javax.swing.JTextField gender__;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name__;
    private javax.swing.JList<String> patientsList;
    private javax.swing.JTextField phonenumber__;
    private javax.swing.JTextField roomnumber__;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
    
}